config/routes.rb
Rails.application.routes.draw do
  get "squares/create"
  get "squares/edit"
  get "bingo_games/index"
  get "bingo_games/new"
  get "bingo_games/create"
  resources :passwords, param: :token
  resources :bingo_games, only: [ :index, :new, :create, :destroy ]
  resources :bingo_games do
    resources :squares, only: [ :create, :update ]
    member do
      get :generate_squares
      get :play_bingo
    end
  end

  root "pages#index"

  get "/login", to: "sessions#new", as: :login
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/signup", to: "users#new", as: :signup
  post "/signup", to: "users#create"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/pages/index.html.erb
<div class="max-w-lg mx-auto pt-8 p-6 bg-white rounded shadow">
  <h1 class="text-4xl pb-4">Welcome to Bingo!</h1>
  <div class="py-2">
    <h2 class="text-2xl">Work on your goals:</h2>
    <div class="flex flex-col">
      <% if @bingo_games.any? %>
        <% @bingo_games.each do |game| %>
          <span class="flex gap-1"><%= link_to game.name, play_bingo_bingo_game_path(game.id), class: "text-blue-600 underline" %><span>(<%= game.percentage_completed %>% Done)</span></span>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="py-2">
    <h2 class="text-2xl">Bingo Games to finish filling out:</h2>
    <div class="flex flex-col">
      <% if @incomplete_bingo_games.any? %>
        <% @incomplete_bingo_games.each do |game| %>
          <%= link_to game.name,
            generate_squares_bingo_game_path(game.id),
            class: "text-blue-600 underline"
          %>
        <% end %>
      <% else %>
        <p>All your games are filled out.</p>
      <% end %>
      <div class="py-4">
        <%= link_to "Start a new Bingo Board", new_bingo_game_path, class: "text-blue-600 underline" %>
      </div>
    </div>
  </div>
</div>